#!/usr/bin/env bash

### BEGIN INIT INFO
# Provides:          manage_my_process
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: manage_my_process init script
# Description:       Manages the manage_my_process script.
### END INIT INFO

SCRIPT="/path/to/manage_my_process"

case "$1" in
  start)
    $SCRIPT start
    ;;
  stop)
    $SCRIPT stop
    ;;
  restart)
    $SCRIPT restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0

