#!/usr/bin/env bash
# let's create the manage_my_process script:

case "$1" in
  start)
    echo "Starting manage_my_process"
    nohup bash -c "while true; do echo 'I am alive!' >> /tmp/my_process; sleep 2; done" >/dev/null 2>&1 &
    echo $! > /var/run/my_process.pid
    ;;
  stop)
    echo "Stopping manage_my_process"
    if [ -f "/var/run/my_process.pid" ]; then
      kill $(cat /var/run/my_process.pid)
      rm /var/run/my_process.pid
    else
      echo "PID file not found. manage_my_process may not be running."
    fi
    ;;
  restart)
    echo "Restarting manage_my_process"
    $0 stop
    sleep 2
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

